### ISSUE TITLE
bad name choice (and there is evidence)

### ISSUE THREAD

**Issue by dret** [w3c/pubsub#10]
i think it's great that the name was changed form what started as a joke to something that can be pronounced and used. but i think this is another incidence of using "class names" as "instance names" that makes things unnecessarily confusing. PubSub is a well-established name for a class of protocols/mechanisms. hijacking this as a name for one specific one is confusing. after a long and painful experience with "XML Schema", where @w3c decided to call _a_ "XML Schema" language "XML Schema", we have a solid body of evidence that this is a bad idea as a naming strategy. so if possible at all, i'd like to encourage the group to come up with a name that is less confusing to the community, and will make it easier for all of us working with protocols and teaching them to avoid terminology confusion if we can. thank you very much!

**Comment by sandhawke** [comment]
Noting more detail at http://dret.typepad.com/dretblog/2016/10/a-pubsub-called-pubsub.html with proposal PubHub.

I'm fairly neutral, tending toward positive, on this.   We didn't spend a lot of time brainstorming new names, and we can still change it pretty easily.

To understand the argument better, though, why isn't HTML a counter-example?   It's a hypertext markup language.   Is it because people don't usually abbreviate hypertext markup language as "HTML"?

Also, why isn't enough to say "W3C PubSub" to disambiguate it?

**Comment by dret** [comment]
> Noting more detail at
> http://dret.typepad.com/dretblog/2016/10/a-pubsub-called-pubsub.html
> with proposal PubHub.

i couldn't stop myself... ;-) the XSD pain still hurts...

> I'm fairly neutral, tending toward positive, on this. We didn't spend a
> lot of time brainstorming new names, and we can still change it pretty
> easily.

very good then. i did notice that the name switch was just prior to FPWD publication, so i hope that renaming wouldn't be such a hassle.

> To understand the argument better, though, why isn't HTML a
> counter-example? It's a hypertext markup language. Is it because people
> don't usually abbreviate hypertext markup language as "HTML"?

to my knowledge, HTML was never used as a name for a class of languages. and i never heard anybody referring to any language other than HTML as *a HTML*, even though if you really wanted to, maybe you could do that. but it would be confusing (hence my issue), so people probably simply don't do it.

> Also, why isn't enough to say "W3C PubSub" to disambiguate it?

could be. XSD tried the same by first branding itself as "W3C XML Schema". it was too complicated and never caught on. it still makes references brittle if people fail to say "W3C", and to me also feels a bit like trying to force people to say "W3C" every time they want to talk about the protocol.

**Comment by tonyg** [comment]
"Web Multicast"?

**Comment by aaronpk** [comment]
Just to get the cross-links in this thread, there is an existing issue about the name change where we tossed around a few ideas and settled on PubSub: #5.

I appreciate the well-written thoughts here, and I have to say I agree with them for the most part. "PubHub" isn't terrible, but I'd also like to hear @julien51 chime in on that since I'm not sure it qualifies as "easily pronounceable" for non-native English speakers.

**Comment by dret** [comment]
> I'm not sure it qualifies as "easily pronounceable" for non-native
> English speakers.

are you specifically referring to french speakers here? ;-) pub-ub?

**Comment by aaronpk** [comment]
I don't think the "b-h" combination is easily pronounceable in any language purely from a phonetic perspective. I'm just saying if that was the part of "PubSubHubbub" that was tripping people up then "PubHub" doesn't change that.

**Comment by dret** [comment]
> I don't think the "b-h" combination is easily pronounceable in any language purely from a phonetic perspective. I'm just saying if that was the part of "PubSubHubbub" that was tripping people up then "PubHub" doesn't change that.

i am not married to "PubHub" at all. i just wanted to suggest something, and actually kind of liked that idea. but i am fine with anything as long as it is not "PubSub" or "Protocol".

**Comment by aaronpk** [comment]
I'm not totally against "PubHub", I just realize I'm biased by being a native English speaker.

Phonetically, "HubPub" is easier to say since the "b-p" end up merging together.

**Comment by dret** [comment]
> I'm not sure it qualifies as "easily pronounceable" for non-native
> English speakers.

are you specifically referring to french speakers here? ;-) pub-ub?

**Comment by dret** [comment]
> Noting more detail at
> http://dret.typepad.com/dretblog/2016/10/a-pubsub-called-pubsub.html
> with proposal PubHub.

i couldn't stop myself... ;-) the XSD pain still hurts...

> I'm fairly neutral, tending toward positive, on this. We didn't spend a
> lot of time brainstorming new names, and we can still change it pretty
> easily.

very good then. i did notice that the name switch was just prior to FPWD 
publication, so i hope that renaming wouldn't be such a hassle.

> To understand the argument better, though, why isn't HTML a
> counter-example? It's a hypertext markup language. Is it because people
> don't usually abbreviate hypertext markup language as "HTML"?

to my knowledge, HTML was never used as a name for a class of languages. 
and i never heard anybody referring to any language other than HTML as 
*a HTML*, even though if you really wanted to, maybe you could do that. 
but it would be confusing (hence my issue), so people probably simply 
don't do it.

> Also, why isn't enough to say "W3C PubSub" to disambiguate it?

could be. XSD tried the same by first branding itself as "W3C XML 
Schema". it was too complicated and never caught on. it still makes 
references brittle if people fail to say "W3C", and to me also feels a 
bit like trying to force people to say "W3C" every time they want to 
talk about the protocol.

**Comment by julien51** [comment]
Hey! Thanks for the feedback. I think PubHub could work. It's not as easy to pronounce as PubSub because H is "silent", but it's not nearly as bad as PubSubHubbub.
So I'll let the  majority decide but I am also in favor in making sure we do not have this conversation too many times because it will get confusing for a lot of people eventually!

**Comment by voxpelli** [comment]
I think PubHub works as well, from swedish perspective and everything. Would prefer it over PubSub and I think it's a definitive improvement over PubSubHubbub while still being more recognizable as stemming from that name than PubSub would.

**Comment by pfefferle** [comment]
It is also working in german, but I don't think it is a better choice. It sounds very similar to PubSub and the difference is only one char, so it might also be problematic in texts.

**Comment by tonyg** [comment]
My favourite is actually still PubSub. I find myself talking about "W3 PubSub" and "W3C PubSub" which gets the point across really well and isn't very verbose, while also having a nice authoritative sound to it :-)

**Comment by sandhawke** [comment]
Another problem with "PubSub": search.   Try google, github, npmjs, etc.   PubSub right now gets you a huge mess of stuff, while pubsubhubbub gets you just the right stuff.

**Comment by dret** [comment]
very good point, @sandhawke, another reason why using a proper name (and not claiming an established concept name) may be a good idea.

**Comment by tonyg** [comment]
Small anecdatum: I get lots of excellent results googling for either 'W3 PubSub' or 'W3C PubSub' (without quotes).

**Comment by aaronpk** [comment]
I just updated the documentation of my hub to refer to "PubSub" instead of "PubSubHubbub". I have to agree, it's pretty confusing since PubSub is a generic term: https://switchboard.p3k.io/

**Comment by aaronpk** [comment]
More discussion happening [in #social](https://chat.indieweb.org/social/2016-11-01#t1478016143947000)

**Comment by aaronpk** [comment]
My current favorite alternative: HubCast

The "hub" is core to the idea of the spec, since the hub coordinates publishers and subscribers. "cast" is from the idea that the spec is used to broadcast a feed to many subscribers.

**Comment by dret** [comment]
On 2016-11-01 17:20, Aaron Parecki wrote:
> My current favorite alternative: HubCast
> The "hub" is core to the idea of the spec, since the hub coordinates
> publishers and subscribers. "cast" is from the idea that the spec is
> used to broadcast a feed to many subscribers.

sounds good to me. i have very little preference for the actual name 
being chosen, so HubCast would be perfect and close this issue.

**Comment by sandhawke** [comment]
Please move discussion to https://www.w3.org/wiki/Socialwg/push-name

**Comment by julien51** [comment]
As of today at the F2F meeting we have agreed on this:
> We reject all pre-exisitng names before today, and we will pick from between WebSub, WebSubscribe, and WebFollow barring any __new__ better names.

**Comment by aaronpk** [comment]
See #62 for the PR that renames the spec, and the motivation for the conclusion.

**Comment by dret** [comment]
thanks! good pick: unique name and no clash with established concepts.

**Comment by sandhawke** [comment]
For amusement value / comic relief, after this was settled, during a break, some group members brainstormed a list of other possible names: https://docs.google.com/document/d/1gfCzLKbH8iVT1MviEU_5Mcgh-OdBtllp5bKZUcgOfuA/edit

**Comment by julien51** [comment]
my heart jump for a second here @sandhawke !

**Comment by sandhawke** [comment]
Oh, seeing activity with this issue title?   Yeah, sorry!
