### ISSUE TITLE
Reference PubSubHubbub

### ISSUE THREAD

**Issue by pfefferle** [w3c/pubsub#11]
Add a section that describes the reference to PubSubHubbub to lower the confusion for existing implementations.

**Comment by dret** [comment]
yes, it would be good to have an informative appendix mentioning the heritage of the protocol. i think it even might be useful to talk about the "original PuSH" that used Atom, and the newer version that moved to being payload-agnostic.

**Comment by aaronpk** [comment]
Does this look good @pfefferle?

**Comment by pfefferle** [comment]
👍
