### ISSUE TITLE
Failed content distribution attempts

### ISSUE THREAD

**Issue by tonyg** [w3c/pubsub#15]
In the draft of 20 Oct 2016, section 6 includes the text:

> The successful response from the subscriber's callback URL MUST be an HTTP [RFC7231] success (2xx) code. The hub MUST consider all other subscriber response codes as failures; that means subscribers MUST NOT use HTTP redirects for moving subscriptions. The response body from the subscriber MUST be ignored by the hub. Hubs SHOULD retry notifications repeatedly until successful (up to some reasonable maximum over a reasonable time period).

What happens when a consistently-failing delivery exceeds the reasonable maximum / reasonable time period?

Proposal: the subscription is terminated/deleted/unsubscribed, and the normal flow of events for a hub-initiated subscription termination is kicked off.

**Comment by dret** [comment]
i think the language as it is is unfortunate and conflicting with itself (SHOULD retry until successful ... up to reasonable ...). i would recommend to make it clear that webhook style delivery always can fail, and that hubs SHOULD document their behavior.
if you look at popular push protocols (APN and GCM and PAP) they have very different behaviors, each for their own reasons. try once is very simple. repeat until maximum time or attempts is already quite a bit more expensive. repeat until delivery or canceled is very expensive and needs an additional management protocol. the complexity of this choice it outside of the scope of PubSub, but acknowledging this complexity and requiring that it is documented might be a good idea.

**Comment by aaronpk** [comment]
It's reasonable to allow hubs to choose their own maximum retry thresholds. I agree that the suggested language about explicitly terminating a subscription would be useful.

How about this for a slightly rephrased version of that sentence, some phrasing borrowed from Webmention:

> Hubs SHOULD retry notifications up to self-imposed limits on the number of times and the overall time period to retry. When the failing delivery exceeds the hub's limits, the hub terminates the subscription.
