### ISSUE TITLE
Lease duration bounds

### ISSUE THREAD

**Issue by tonyg** [w3c/pubsub#18]
In the draft of 20 Oct 2016, no mention is made of acceptable values for `hub.lease_seconds` other than it be a "number".
1. Are non-integers accepted?
2. Are negative numbers accepted?
3. Are numbers in non-decimal bases accepted?

If non-integers are accepted, it might be worth pointing out that hub implementations should take care to properly handle very small values such as `0` or `0.000001`. (And perhaps that they may round to the nearest whole number of seconds.)

I suggest forbidding negative numbers :-)

I also suggest forbidding non-decimal bases. (Some languages' standard libraries will automatically interpret '0xaa' as decimal 170.)

It might be simplest to specify that `hub.lease_seconds` must be a non-empty sequence of ASCII decimal digit characters (plus, perhaps, a signifier of an unbounded duration, depending on treatment of issue #17).

Finally, some very large integers, e.g. those larger than 2^31, 2^53 or 2^63, may also cause problems for hub implementations written in some programming languages. Would a note on reasonable ranges of lease times be in order? Or perhaps a note pointing out explicitly that no limit is in place, and that implementations should be prepared to deal with very large values?

**Comment by aaronpk** [comment]
I believe the intent was to allow only positive decimal integers. It's probably worth formalizing that with some short text. Given that 2^32 is the entirety of the valid unix timestamps, that would seem a natural upper bound, although in practice I believe the maximum lease duration is several orders of magnitude shorter. 

There is also a benefit of using shorter lease durations such as a week, as it ensures that subscribers will periodically re-subscribe, allowing hubs to stop attempting delivery to subscribers that may later be offline.

**Comment by tonyg** [comment]
Re: very large integers, I should clarify: I meant that some languages will have trouble *parsing* such strings, totally independent of the absurdity of actually claiming a lease lasting that long :-) There's no need to actually have an upper bound; implementations will have their own upper bound preferences.

**Comment by aaronpk** [comment]
@tonyg did that PR address the issue for you?

**Comment by tonyg** [comment]
Yep! I'm happy with "non-negative"; just to check though, you wrote above that the intent was "to allow only positive decimal integers", but if you're happy with "non-negative" too then we're all happy :-)

**Comment by aaronpk** [comment]
Let's address whether "0" is valid and what it means in #17
