### ISSUE TITLE
use subscription resource

### ISSUE THREAD

**Issue by dret** [w3c/pubsub#20]
this is a design change issue. what about using a subscription resource? this could make the protocol much more RESTful and also solve some existing issues more elegantly and easily. assuming you POST the subscription request, let's do it like this:
- a subscription resource is created and the resource URI returned
- the Sunset header [1] of the resource says how long it lives (if it expires)
- unsubscriptions DELETE the subscription resource
- servers may support GET of the subscription resource to provide subscription metadata (this is for example how delivery attempts could be signaled, see #15)

[1] http://webconcepts.info/specs/IETF/I-D/wilde-sunset-header

**Comment by aaronpk** [comment]
This is a pretty big design change with no obvious benefits, and would break every existing implementation. Without any concrete examples of problems this solves, I don't think this is worth considering at all.

> this could make the protocol much more RESTful

This is not an inherent benefit and should not be used as an argument to completely change the design of a spec especially after it's been developed and deployed for so many years.

**Comment by julien51** [comment]
Closing for now. Feel free to re-open.

**Comment by akuckartz** [comment]
@julien51 Please do not close issues without providing a reason. Is this based on a WG decision?

**Comment by sandhawke** [comment]
To rephrase @aaronpk's comment: is there a problem with the protocol as currently specified that this would address?    I can certainly see how it might look nicer, but are there measurable ways it would behave better?   After years of doing it one way, that seems to work fine, the bar to switching is higher.

**Comment by dret** [comment]
On 2016-11-19 04:52, Sandro Hawke wrote:
> To rephrase @aaronpk <https://github.com/aaronpk>'s comment: is there a
> problem with the protocol as currently specified that this would
> address? I can certainly see how it might look nicer, but are there
> measurable ways it would behave better? After years of doing it one way,
> that seems to work fine, the bar to switching is higher.

i agree that the bar to change is high, and i am fine if it's considered 
too high. from what i can tell, resource-oriented designs tend to have 
better patterns for extensibility (additional interactions with the 
resource) and addressibility (resources have identifiers that can be 
handed around between clients), but again, these are just general design 
aspects and not something that fixes a current well-known issue with the 
protocol as it is.

i am fine if this issue gets closed because it is too late in the game 
to make substantial protocol changes like this.

**Comment by julien51** [comment]
@akuckartz sorry if I closed this too early. I assumed people where satisfied with the comments given earlier (given the 👍 on them).
