### ISSUE TITLE
algorithm names

### ISSUE THREAD

**Issue by dret** [w3c/pubsub#21]
is the list of algorithm names given in https://www.w3.org/TR/pubsub/#recognized-algorithm-names a closed and stable list? if not (and this should be looking forward a few years), maybe it would be a good idea to have a registry for them (with the four listed values as initial contents), so that new names can be added as they may get added by implementations and subsequently should be discoverable through the registry.

**Comment by aaronpk** [comment]
The entries in that list are from FIPS PUB 180-4 (as cited in that section) so maybe that can be the "registry"?

**Comment by dret** [comment]
> The entries in that list are from FIPS PUB 180-4 (as cited in that section) so maybe that can be the "registry"?

sounds reasonable. but then maybe be more clear about whether the list as provided by PubSub is a closed list and will not change, or that it is simply a snapshot and if FIPS PUB 180-4 changes, then so will the values allowed in PubSub.

**Comment by aaronpk** [comment]
@dret  does that latest commit address the issue for you?

**Comment by dret** [comment]
maybe change "The following algorithms are currently added as recognized algorithm names." to "The following algorithms are the initially registered algorithm names, based on the current content of the referenced registry." ("currently added" sounds a bit odd to me), but that's just a nit.
generally speaking, i think it's good enough as it makes clear that the list of algorithm names is evolving, and it identifies the registry to use for lookup.

**Comment by aaronpk** [comment]
Thanks. I agree that sounds a little awkward, so I rephrased it slightly like you suggested.
