### ISSUE TITLE
Validation: synchronous?

### ISSUE THREAD

**Issue by tonyg** [w3c/pubsub#22]
In the draft of 20 Oct 2016, section 4.1 says:

> Any failures to confirm the subscription action MUST leave the subscription state unchanged.

And section 4.1.2 says:

> The hub MUST respond to a subscription request with an HTTP [RFC7231] 202 "Accepted" response to indicate that the request was received and will now be verified (Section 5.3 ) and validated (Section 5.2 ) by the hub. The hub SHOULD perform the verification and validation of intent as soon as possible.

And section 4.2 says:

> If (and when), the subscription is accepted, the hub MUST perform the verification of intent of the subscriber.

My questions are:
1. Does "confirmation of the subscription action" include verification of intent?
   1. for the initial subscription?
   2. for subsequent edits/renewals?
2. May the hub answer 202 prior to verification of intent?
3. May the hub verify intent before making a decision about how to respond to a subscription request?
4. If so, if verification fails, must the hub answer 202, or may it answer some other code?
5. If so, what code(s) (and their meanings) would be appropriate for failure to verify intent?

My guesses, based on the spec and intuition, are that the answers are/should be:
1. yes to both
2. yes, but it doesn't have to
3. yes
4. it may answer some other code
5. I'm not sure yet

**Comment by julien51** [comment]
1. yes to both
2. yes. 
3. No. This is a difference we introduced with earlier version of PubSubHubbub where all subscriptions are now async. The reason for this is simplification. "sync" is basically a subset of "async" now. 
4. The hub will always respond 202 because verification is always async.
5. N/A

**Comment by tonyg** [comment]
Thank you @julien51! I will suggest some wording for clarification in a PR.

**Comment by julien51** [comment]
Thanks, closing for now and hoping we can merge this soon!
