### ISSUE TITLE
Include a spec version number?

### ISSUE THREAD

**Issue by tonyg** [w3c/pubsub#29]
It's often said^{citation needed} that protocols absolutely must be versioned. Does that apply here? Would we want something like a "hub.version=..." parameter in (un)subscription requests and in callback invocations?

Especially where there might be small differences between PSHB 0.3/0.4 and this spec.

**Comment by voxpelli** [comment]
Better to make changes such that server and clients can understand them and adapt to them. Until a change can't be solved in any other way than adding a version number then no version number should be added I think.

**Comment by akuckartz** [comment]
Can you provide a use case?

**Comment by tonyg** [comment]
I think I agree with what @voxpelli wrote, and withdraw the suggestion. Thanks!
