### ISSUE TITLE
Language/direction/localizability of error message

### ISSUE THREAD

**Issue by aaronpk** [w3c/pubsub#33]
> In the event of an error, hubs should return a description of the error in the response body as plain text.

Similar to [Micropub #36](https://github.com/w3c/Micropub/issues/36), this will get flagged by the i18n review. The solution we arrived at with Micropub was to clarify that this message is intended for the developer, and not intended to be user visible. This way we can avoid the need for handling text direction and localization of the string.

> In the event of an error, hubs should return a description of the error in the response body as plain text, used to assist the client developer in understanding the error. This is not meant to be shown to the end user.

**Comment by julien51** [comment]
👍

**Comment by akuckartz** [comment]
The issue https://github.com/w3c/Micropub/issues/36 is still tagged "Waiting For Commentor".
