### ISSUE TITLE
Discovery inconsistency

### ISSUE THREAD

**Issue by aaronpk** [w3c/pubsub#37]
In the [first paragraph of Discovery](https://www.w3.org/TR/pubsub/#discovery), the spec currently says that publishers MUST include an HTTP `Link` header. In the second paragraph, it says that subscribers MAY fall back to other methods of discovering the hub and topic, and suggests embedded link elements for XML and HTML documents. The inconsistency in the spec arises from the fact that if publishers are required to advertise the values in Link headers, then there is no need for consumers to check other places.

Either the spec should drop all mention of alternative methods and require publishers and consumers use HTTP headers, or it should explicitly allow publishers to advertise the values in the HTML or XML document.

We addressed this in Webmention by saying that senders are required to support both HTTP header and HTML based discovery. https://webmention.net/draft/#sender-discovers-receiver-webmention-endpoint

Personally, I would prefer not to limit discovery to only HTTP headers, since that precludes some websites from using it, so would like to do what Webmention did. Something along the lines of:
- Publishers SHOULD advertise the hub and topic in HTTP Link headers, and if the topic URL is HTML or XML, MAY instead advertise the values with a `<link>` tag.
- Subscribers MUST first check HTTP Link headers, and if the content type is HTML or XML and no values were found in the headers, then MUST check for `<link>` tags.

**Comment by voxpelli** [comment]
+1, this would make eg. Jekyll blogs, which can't use Link-headers, spec-compliant and would better reflect real world deployments of this spec

**Comment by dret** [comment]
> On Oct 29, 2016, at 20:39, Pelle Wessman <notifications@github.com> wrote:
> +1, this would make eg. Jekyll blogs, which can't use Link-headers, spec-compliant and would better reflect real world deployments of this spec
> 

+1, discovery via link relation should be the preferred method (and the link relation should be allowed to be used in any way that publishers prefer), but in the end, if i magically know the hub i want to interact with, that should be allowed by the spec as well.

**Comment by julien51** [comment]
👍 
@aaronpk I think your suggestion of how to handle this is the right one and I believe it complies by the robustness principle, so all good for me! Unless somebody disagrees with this, I believe I'll go ahead and submit a PR.
