### ISSUE TITLE
Drop .host-meta discovery if no known implementations

### ISSUE THREAD

**Issue by aaronpk** [w3c/pubsub#40]
Are there any known implementations of advertising the hub using the `.host-meta` method? If not, it's probably worth dropping that from the list of supported discovery methods.

**Comment by tantek** [comment]
FWIW we also made a similar decision for Webmention and other SWWG specs, based on that and group resolution to prefer "follow your nose" methods of discovery, settling on link rels being sufficient.

**Comment by julien51** [comment]
I'm ok with that.

**Comment by julien51** [comment]
Actually... let me change my mind :)
For these content types which do not have a clear "linking" mechanism and which are hosted on platforms which do not allow for `Link` headers (Jekyll + github), this is a convenient way to set up hub discovery. So I'm in favor of keeping it!

**Comment by aaronpk** [comment]
Do you know of any publishers or subscribers that ever actually implemented .well-known discovery?

**Comment by julien51** [comment]
Good point. I don't. 
But it's cheap to keep it.

**Comment by aaronpk** [comment]
It's actually not cheap to keep it. At the very least we should mark it as an "at risk" feature. In order to get to Recommendation, each feature of the spec must have at least two implementations. Part of the testing tool I'm building is keeping track of how many implementations implement each feature of the spec. You can see what this will look like for [Micropub](https://micropub.rocks/reports), and the less pretty version for [Webmention](https://webmention.net/implementation-reports/summary/). 

Keeping this feature also means that:
1) Every subscriber will have to check for the .well-known value because they can't assume the publisher will send a link header
2) I will have to build support for it into pubsub.rocks

**Comment by julien51** [comment]
Since it's already in the spec, we _cannot_ remove it. BUT, we should put it "at risk" so we can later on deprecate if we see no usage of it.
Also, the current wording around that is not clear enough and uses the wrong link. I believe @aaronpk will clarify!

**Comment by pfefferle** [comment]
the correct link to the host-meta spec is https://tools.ietf.org/html/rfc6415 (instead of the well-known) and the correct URL path is `/.well-known/host-meta` (instead of `.host-meta`)

**Comment by akuckartz** [comment]
:+1: for "at risk"

**Comment by aaronpk** [comment]
This has been done in #61
