### ISSUE TITLE
[FPWD blocker] consider renaming the spec

### ISSUE THREAD

**Issue by tantek** [w3c/pubsub#5]
The editor requested renaming the spec for something friendlier to non-English speakers. Group generally agreed.

Please bikeshed.

**Comment by julien51** [comment]
I don't necessarily WANT to change... but I think this has been a recurring "issue" for a lot of people. If now is a better time to have this discussion, I think we could have it. 
Suggestions: webpubsub, pushhook, httphook.

**Comment by aaronpk** [comment]
Or just "PubSub"

**Comment by julien51** [comment]
"PubSub" is good for me if you (w3c) don't think the naming conflict with XEP60 (XMPP), redis and others is ok.

**Comment by pfefferle** [comment]
What about WebPubSub? To keep the same pattern as Webmention or WebFinger...

**Comment by pfefferle** [comment]
Oh, just saw that @julien51 already proposed this... So my +1 one for Webpubsub :)

**Comment by dissolve** [comment]
I think its good to keep a recognizable name for those who have already used pubsubhubbub , so I think "pubsub" is good in that sense.

**Comment by aaronpk** [comment]
-1 to "WebPubSub": I don't think "WebPubSub" better enough than "PubSubHubbub" to justify confusion that would ensue with renaming it. 

I'm pretty much neutral on "PubSub". It is at least short, but isn't super distinctive.

**Comment by tantek** [comment]
BTW the group resolved on "PubSub" at the f2f after I filed this issue:

https://www.w3.org/wiki/Socialwg/2016-09-23-minutes#Pubsubhubbub

"RESOLUTION: Use shortname of pubsub for shortname for now"

If there are any objections to PubSub (especially with new information), please say so before next Tuesday 2016-10-18!

**Comment by julien51** [comment]
Great news!

**Comment by tantek** [comment]
We resolved this and published a FPWD, so this particular issue is resolved and closed. Leaving the other one (10) open for any iterative discussion.
